#!/usr/bin/env python3
"""Export paper bundle + README_FOR_AI.md for AI-assisted writing.

Copies paper_assets (tables/figures/analysis + notes), summaries from outputs/,
configs (P0/P5/J3), lite run artifacts, data_protocol; optional full trees / checkpoints.

  python scripts/export_paper_bundle.py
  python scripts/export_paper_bundle.py --out D:/paper_bundle_task3 --include-checkpoints
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from typing import Iterable, List

ROOT = Path(__file__).resolve().parents[1]

CANONICAL_RUN_DIRS = [
    "task3_v2_1_baseline_same_split",
    "task3_v3_1_oracle_matched_trigger_same_split",
    "task3_J3_joint_detach_false",
]
SUPP_RUN_DIRS = [
    "task3_J1_joint_calib_only",
    "task3_J2_joint_detach_true",
    "task3_J3_calib0",
    "task3_J3_semantic_control",
]
MULTISEED_RUN_DIRS = [
    "task3_P0_baseline_seed40",
    "task3_P0_baseline_seed41",
    "task3_P5_oracle_matched_trigger_seed40",
    "task3_P5_oracle_matched_trigger_seed41",
    "task3_J3_joint_detach_false_seed40",
    "task3_J3_joint_detach_false_seed41",
]
CROSS_SPLIT_RUN_DIRS = [
    "task3_P0_baseline_splitB",
    "task3_P0_baseline_splitB_seed40",
    "task3_P0_baseline_splitC",
    "task3_P5_oracle_matched_trigger_splitB",
    "task3_P5_oracle_matched_trigger_splitB_seed40",
    "task3_P5_oracle_matched_trigger_splitC",
    "task3_J3_joint_detach_false_splitB",
    "task3_J3_joint_detach_false_splitB_seed40",
    "task3_J3_joint_detach_false_splitC",
]
SUMMARY_FILES = [
    "multiseed_analysis.json",
    "multiseed_per_seed.csv",
    "cross_split_analysis.json",
    "cross_split_per_run.csv",
    "semantic_control_result.json",
    "warmup_ablation.json",
    "final_leaderboard.json",
    "line_a_summary.json",
    "task3_v2_1_minimal_matrix_summary.json",
    "task3_compare_summary.json",
]
CONFIG_FILES = [
    "configs/task3_v2_1_baseline.yaml",
    "configs/task3_v3_1_oracle_matched_trigger.yaml",
    "configs/task3_J3_joint_detach_false.yaml",
]
ROOT_FILES = ["cldice_summary.json"]
PAPER_MARKDOWN = ["writing_support_notes.md", "manuscript_assets_manifest.md"]
DOCS_FILES = ["docs/task3_j3_paper_closure.md"]
RUN_ARTIFACT_NAMES = [
    "config_used.yaml",
    "threshold_metrics.json",
    "val_metrics.json",
    "hard_patch_metrics.json",
    "difficulty_stats.json",
    "weight_stats.json",
    "history.json",
    "debug_first_weighted_batch.json",
    "train_curves.png",
    "pred_vs_gt_scatter.png",
    "pred_sci_hist.png",
]


def _copy_file(src: Path, dst: Path) -> bool:
    if not src.is_file():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def _copy_tree_selective(src: Path, dst: Path, *, include_checkpoints: bool) -> None:
    def ignore_fn(_dir: str, names: List[str]) -> List[str]:
        skip: List[str] = []
        for n in names:
            p = Path(_dir) / n
            if n == "__pycache__":
                skip.append(n)
            elif p.is_dir() and n == "patches":
                skip.append(n)
            elif (
                not include_checkpoints
                and p.is_file()
                and p.suffix.lower() in (".pt", ".pth", ".ckpt")
            ):
                skip.append(n)
        return skip

    if src.is_dir():
        shutil.copytree(src, dst, ignore=ignore_fn, dirs_exist_ok=True)


def _copy_run_lite(src_dir: Path, dst_dir: Path, *, include_checkpoints: bool) -> List[str]:
    if not src_dir.is_dir():
        return [f"MISSING: {src_dir.name}"]
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied: List[str] = []
    for name in RUN_ARTIFACT_NAMES:
        s = src_dir / name
        if s.is_file():
            shutil.copy2(s, dst_dir / name)
            copied.append(name)
    if include_checkpoints:
        for ck in ("best_model.pt", "last_model.pt"):
            s = src_dir / ck
            if s.is_file():
                shutil.copy2(s, dst_dir / ck)
                copied.append(ck)
    return copied


def write_readme(
    out: Path, *, include_checkpoints: bool, copied_runs: dict[str, List[str]]
) -> None:
    lines = [
        "# README_FOR_AI — Task 3 paper bundle",
        "",
        "Generated by `scripts/export_paper_bundle.py`.",
        "Quantitative claims: **patch / group-split protocol** (`configs/`, `data_protocol/`).",
        "",
        "## Canonical methods (`runs_canonical/`)",
        "",
        "| Role | Folder |",
        "|------|--------|",
        "| P0 | `task3_v2_1_baseline_same_split` |",
        "| P5 | `task3_v3_1_oracle_matched_trigger_same_split` |",
        "| J3 | `task3_J3_joint_detach_false` |",
        "",
        "**Primary metric:** `hard_dice_mean` @ `best_hard_dice_threshold` in each run's "
        "`threshold_metrics.json`.",
        "**Secondary:** Dice/Recall @ 0.5 in `val_metrics.json` / `threshold_metrics.json`.",
        "",
        "## Contents",
        "",
        "- `paper_assets/` — tables/, figures/, analysis/, writing_support_notes.md, "
        "manuscript_assets_manifest.md",
        "- `summaries/` — multiseed, cross_split, semantic_control, warmup_ablation, etc.",
        "- `configs/` — P0, P5, J3 yaml",
        "- `runs_supplementary/` — J1, J2, J3_calib0, semantic control",
        "- `runs_multiseed/`, `runs_cross_split/` — unless `--skip-multiseed-crosssplit`",
        "- `data_protocol/` — patch_metadata.csv, split_*.json (no patch images)",
        "- `cldice_summary.json` at bundle root if present in repo",
        "",
        f"**Checkpoints included:** {'yes' if include_checkpoints else 'no'}",
        "",
        "## Copy log",
        "",
    ]
    for section, items in copied_runs.items():
        lines.append(f"### {section}")
        for line in items[:120]:
            lines.append(f"- {line}")
        lines.append("")
    lines.extend(
        [
            "## Important",
            "",
            "If the paper uses **DRIVE/CHASE/HRF**, this bundle does not replace those runs; "
            "use for definitions + supplementary patch evidence.",
            "",
        ]
    )
    (out / "README_FOR_AI.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Export paper bundle for AI-assisted writing.")
    ap.add_argument("--out", type=Path, default=ROOT / "paper_bundle_task3")
    ap.add_argument("--include-checkpoints", action="store_true")
    ap.add_argument("--full-runs", action="store_true")
    ap.add_argument("--skip-multiseed-crosssplit", action="store_true")
    args = ap.parse_args()
    out = args.out.resolve()
    if not out.is_absolute():
        out = (ROOT / out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    log: dict[str, List[str]] = {}

    pa = out / "paper_assets"
    pa.mkdir(parents=True, exist_ok=True)
    for sub in ("tables", "figures", "analysis"):
        s = ROOT / sub
        if s.is_dir():
            shutil.copytree(s, pa / sub, dirs_exist_ok=True)
    for md in PAPER_MARKDOWN:
        f = ROOT / md
        if f.is_file():
            shutil.copy2(f, pa / md)
    log["paper_assets"] = ["tables/, figures/, analysis/"] + PAPER_MARKDOWN

    cd = out / "configs"
    cd.mkdir(parents=True, exist_ok=True)
    cl: List[str] = []
    for rel in CONFIG_FILES:
        s = ROOT / rel
        if s.is_file():
            shutil.copy2(s, cd / s.name)
            cl.append(s.name)
        else:
            cl.append(f"MISSING {rel}")
    log["configs"] = cl

    sm = out / "summaries"
    sm.mkdir(parents=True, exist_ok=True)
    sl: List[str] = []
    for name in SUMMARY_FILES:
        if _copy_file(ROOT / "outputs" / name, sm / name):
            sl.append(name)
        else:
            sl.append(f"(missing) {name}")
    log["summaries"] = sl

    for name in ROOT_FILES:
        if _copy_file(ROOT / name, out / name):
            log.setdefault("root", []).append(name)

    dd = out / "docs"
    dd.mkdir(parents=True, exist_ok=True)
    for rel in DOCS_FILES:
        s = ROOT / rel
        if s.is_file():
            shutil.copy2(s, dd / Path(rel).name)
    log["docs"] = [Path(x).name for x in DOCS_FILES if (ROOT / x).is_file()]

    dp = out / "data_protocol"
    dp.mkdir(parents=True, exist_ok=True)
    dl: List[str] = []
    if _copy_file(
        ROOT / "outputs" / "task1_topo_v3" / "patch_metadata.csv",
        dp / "patch_metadata.csv",
    ):
        dl.append("patch_metadata.csv")
    else:
        dl.append("MISSING patch_metadata.csv")
    sd = ROOT / "outputs" / "task3_split"
    if sd.is_dir():
        for jf in sorted(sd.glob("*.json")):
            shutil.copy2(jf, dp / jf.name)
            dl.append(jf.name)
    log["data_protocol"] = dl

    def export(names: Iterable[str], sub: str) -> List[str]:
        res: List[str] = []
        for name in names:
            src = ROOT / "outputs" / name
            dst = out / sub / name
            if not src.is_dir():
                res.append(f"MISSING {name}")
                continue
            if args.full_runs:
                if dst.exists():
                    shutil.rmtree(dst)
                _copy_tree_selective(src, dst, include_checkpoints=args.include_checkpoints)
                res.append(f"{name}/ (tree)")
            else:
                r = _copy_run_lite(src, dst, include_checkpoints=args.include_checkpoints)
                res.append(f'{name}: {", ".join(r)}')
        return res

    log["runs_canonical"] = export(CANONICAL_RUN_DIRS, "runs_canonical")
    log["runs_supplementary"] = export(SUPP_RUN_DIRS, "runs_supplementary")
    if not args.skip_multiseed_crosssplit:
        log["runs_multiseed"] = export(MULTISEED_RUN_DIRS, "runs_multiseed")
        log["runs_cross_split"] = export(CROSS_SPLIT_RUN_DIRS, "runs_cross_split")

    write_readme(out, include_checkpoints=args.include_checkpoints, copied_runs=log)
    print(f"Paper bundle: {out}")
    print("  README_FOR_AI.md")


if __name__ == "__main__":
    main()
